/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Body2 struct {

	Template string `json:"template,omitempty"`

	Title string `json:"title,omitempty"`

	Credentials interface{} `json:"credentials,omitempty"`

	Config interface{} `json:"config,omitempty"`
}
