/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Body1 struct {

	Provider string `json:"provider,omitempty"`

	Label string `json:"label,omitempty"`

	Stack string `json:"stack,omitempty"`

	Credential string `json:"credential,omitempty"`

	Meta ComputeProviderCreateMeta `json:"meta,omitempty"`
}
