/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Body3 struct {

	Provider string `json:"provider,omitempty"`

	UseDefaults bool `json:"useDefaults,omitempty"`
}
