/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ComputeProviderCreateMeta struct {

	InstanceType string `json:"instance_type,omitempty"`

	Region string `json:"region,omitempty"`

	Image string `json:"image,omitempty"`

	StorageSize float32 `json:"storage_size,omitempty"`
}
