/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type InlineResponse200 struct {

	Json string `json:"json,omitempty"`

	Yaml string `json:"yaml,omitempty"`

	Defaults InlineResponse200Defaults `json:"defaults,omitempty"`
}
