/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JCombinedAppStorage struct {

	Id string `json:"_id,omitempty"`

	AccountId string `json:"accountId,omitempty"`

	Bucket interface{} `json:"bucket,omitempty"`
}
