/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JCredentialData struct {

	Id string `json:"_id,omitempty"`

	Identifier string `json:"identifier,omitempty"`

	Meta interface{} `json:"meta"`

	OriginId string `json:"originId"`
}
