/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type JCustomPartials struct {

	Id string `json:"_id,omitempty"`

	Name string `json:"name,omitempty"`

	PartialType string `json:"partialType,omitempty"`

	Partial interface{} `json:"partial,omitempty"`

	IsActive bool `json:"isActive,omitempty"`

	IsPreview bool `json:"isPreview,omitempty"`

	PreviewInstance string `json:"previewInstance,omitempty"`

	ViewInstance string `json:"viewInstance,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	PublishedAt time.Time `json:"publishedAt,omitempty"`
}
