/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JEarnedReward struct {

	Id string `json:"_id,omitempty"`

	OriginId string `json:"originId"`

	Type_ string `json:"type,omitempty"`

	Unit string `json:"unit,omitempty"`

	Amount float32 `json:"amount,omitempty"`
}
