/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JGroupRole struct {

	Id string `json:"_id,omitempty"`

	Title string `json:"title,omitempty"`

	Value string `json:"value,omitempty"`

	IsConfigureable string `json:"isConfigureable,omitempty"`

	IsDefault bool `json:"isDefault,omitempty"`
}
