/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JGroupLimit struct {

	Id string `json:"_id,omitempty"`

	Name string `json:"name,omitempty"`

	Member float32 `json:"member,omitempty"`

	ValidFor float32 `json:"validFor,omitempty"`

	InstancePerMember float32 `json:"instancePerMember,omitempty"`

	AllowedInstances []string `json:"allowedInstances,omitempty"`

	MaxInstance float32 `json:"maxInstance,omitempty"`

	StoragePerInstance float32 `json:"storagePerInstance,omitempty"`

	Restrictions JGroupLimitRestrictions `json:"restrictions,omitempty"`
}
