/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JGroupLimitRestrictions struct {

	Supports []string `json:"supports,omitempty"`

	Provider []string `json:"provider,omitempty"`

	Resource []string `json:"resource,omitempty"`

	Custom interface{} `json:"custom,omitempty"`
}
