/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JGroupCustomize struct {

	CoverPhoto string `json:"coverPhoto,omitempty"`

	Logo string `json:"logo,omitempty"`

	ChatlioId string `json:"chatlioId,omitempty"`
}
