/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type JInvitation struct {

	Id string `json:"_id,omitempty"`

	Code string `json:"code"`

	Email string `json:"email"`

	Hash string `json:"hash"`

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	GroupName string `json:"groupName"`

	Status string `json:"status,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	ModifiedAt time.Time `json:"modifiedAt,omitempty"`

	Role string `json:"role,omitempty"`

	InviterId string `json:"inviterId,omitempty"`
}
