/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type JMachine struct {

	Id string `json:"_id,omitempty"`

	Uid string `json:"uid"`

	QueryString string `json:"queryString,omitempty"`

	IpAddress string `json:"ipAddress,omitempty"`

	Domain string `json:"domain,omitempty"`

	Provider string `json:"provider"`

	Label string `json:"label,omitempty"`

	Slug string `json:"slug,omitempty"`

	Provisioners []string `json:"provisioners,omitempty"`

	Credential string `json:"credential,omitempty"`

	Users []interface{} `json:"users,omitempty"`

	Groups []interface{} `json:"groups,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	Status JMachineStatus `json:"status,omitempty"`

	Meta interface{} `json:"meta,omitempty"`

	Assignee JMachineAssignee `json:"assignee,omitempty"`

	GeneratedFrom JMachineGeneratedFrom `json:"generatedFrom,omitempty"`

	ChannelId string `json:"channelId,omitempty"`
}
