/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type JMachineStatus struct {

	ModifiedAt time.Time `json:"modifiedAt,omitempty"`

	Reason string `json:"reason,omitempty"`

	State string `json:"state,omitempty"`
}
