/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JMachineGeneratedFrom struct {

	TemplateId string `json:"templateId,omitempty"`

	Revision string `json:"revision,omitempty"`
}
