/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type JPasswordRecovery struct {

	Id string `json:"_id,omitempty"`

	Email string `json:"email,omitempty"`

	Username string `json:"username,omitempty"`

	Token string `json:"token,omitempty"`

	RedeemedAt time.Time `json:"redeemedAt,omitempty"`

	ExpiresAt time.Time `json:"expiresAt,omitempty"`

	Expires bool `json:"expires,omitempty"`

	Status string `json:"status,omitempty"`

	RequestedAt time.Time `json:"requestedAt,omitempty"`
}
