/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JProposedDomain struct {

	Id string `json:"_id,omitempty"`

	Domain string `json:"domain,omitempty"`

	Machines []interface{} `json:"machines,omitempty"`

	Proxy JProposedDomainProxy `json:"proxy,omitempty"`

	Meta interface{} `json:"meta,omitempty"`

	Group string `json:"group,omitempty"`
}
