/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JProposedDomainProxy struct {

	Mode string `json:"mode,omitempty"`

	Username string `json:"username,omitempty"`

	ServiceName string `json:"serviceName,omitempty"`

	Key string `json:"key,omitempty"`

	FullUrl string `json:"fullUrl,omitempty"`
}
