/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JProvisioner struct {

	Id string `json:"_id,omitempty"`

	Slug string `json:"slug"`

	Label string `json:"label,omitempty"`

	Type_ string `json:"type,omitempty"`

	ContentSum string `json:"contentSum,omitempty"`

	Content interface{} `json:"content,omitempty"`

	AccessLevel string `json:"accessLevel,omitempty"`

	OriginId string `json:"originId"`

	Group string `json:"group,omitempty"`

	Meta interface{} `json:"meta,omitempty"`
}
