/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type JReward struct {

	Id string `json:"_id,omitempty"`

	Type_ string `json:"type,omitempty"`

	Unit string `json:"unit,omitempty"`

	Amount float32 `json:"amount,omitempty"`

	SourceCampaign string `json:"sourceCampaign,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	ProvidedBy string `json:"providedBy,omitempty"`

	OriginId string `json:"originId"`

	Confirmed bool `json:"confirmed,omitempty"`
}
