/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type JRewardCampaign struct {

	Id string `json:"_id,omitempty"`

	Name string `json:"name"`

	Slug string `json:"slug,omitempty"`

	IsActive bool `json:"isActive,omitempty"`

	Type_ string `json:"type,omitempty"`

	Unit string `json:"unit,omitempty"`

	InitialAmount float32 `json:"initialAmount,omitempty"`

	MaxAmount float32 `json:"maxAmount,omitempty"`

	PerEventAmount float32 `json:"perEventAmount,omitempty"`

	GivenAmount float32 `json:"givenAmount,omitempty"`

	StartDate time.Time `json:"startDate,omitempty"`

	EndDate time.Time `json:"endDate,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
