/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type JSession struct {

	Id string `json:"_id,omitempty"`

	ClientId string `json:"clientId,omitempty"`

	ClientIP string `json:"clientIP,omitempty"`

	Username string `json:"username,omitempty"`

	OtaToken string `json:"otaToken,omitempty"`

	GroupName string `json:"groupName,omitempty"`

	GuestId float32 `json:"guestId,omitempty"`

	TerminalId string `json:"terminalId,omitempty"`

	SessionBegan time.Time `json:"sessionBegan,omitempty"`

	GuestSessionBegan time.Time `json:"guestSessionBegan,omitempty"`

	LastAccess time.Time `json:"lastAccess,omitempty"`

	ForeignAuth JSessionForeignAuth `json:"foreignAuth,omitempty"`

	ReturnUrl string `json:"returnUrl,omitempty"`

	ForeignAuthType string `json:"foreignAuthType,omitempty"`

	Impersonating bool `json:"impersonating,omitempty"`

	SessionData interface{} `json:"sessionData,omitempty"`
}
