/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JSessionForeignAuth struct {

	Gitlab interface{} `json:"gitlab,omitempty"`

	Github interface{} `json:"github,omitempty"`

	Facebook interface{} `json:"facebook,omitempty"`

	Linkedin interface{} `json:"linkedin,omitempty"`
}
