/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JStackTemplateTemplate struct {

	// Stack template content in JSON format
	Content string `json:"content,omitempty"`

	// Sum of stringified JSON content, auto-generated
	Sum string `json:"sum,omitempty"`

	// Details data for stack template
	Details interface{} `json:"details,omitempty"`

	// Stack template content in YAML format
	RawContent string `json:"rawContent,omitempty"`
}
