/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JStackTemplate struct {

	Id string `json:"_id,omitempty"`

	Machines []interface{} `json:"machines,omitempty"`

	// Title of this stack template
	Title string `json:"title"`

	// Unique slug of stack template
	Slug string `json:"slug"`

	// Stack template description
	Description string `json:"description,omitempty"`

	// Private config data for stack template
	Config interface{} `json:"config,omitempty"`

	AccessLevel string `json:"accessLevel,omitempty"`

	OriginId string `json:"originId"`

	Meta interface{} `json:"meta,omitempty"`

	Group string `json:"group"`

	Template JStackTemplateTemplate `json:"template,omitempty"`

	Credentials interface{} `json:"credentials,omitempty"`
}
