/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type JTeamInvitation struct {

	Id string `json:"_id,omitempty"`

	Code string `json:"code"`

	Email string `json:"email"`

	GroupName string `json:"groupName,omitempty"`

	Status string `json:"status,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
