/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JUrlAlias struct {

	Id string `json:"_id,omitempty"`

	Alias string `json:"alias,omitempty"`

	Target string `json:"target,omitempty"`
}
