/* 
 * Koding API
 *
 * Koding API for integrating your application with Koding services
 *
 * OpenAPI spec version: 0.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type JUserRegisteredFrom struct {

	Ip string `json:"ip,omitempty"`

	Country string `json:"country,omitempty"`

	Region string `json:"region,omitempty"`
}
